apiVersion: apps/v1
kind: Deployment
metadata:
  name: profstankin-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profstankin-front
  template:
    metadata:
      labels:
        app: profstankin-front
    spec:
      containers:
        - name: frontend
          image: chouqe/profstankin-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: profstankin-front-svc
spec:
  selector:
    app: profstankin-front
  ports:
    - port: 80
      targetPort: 3000
