apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-api-config
data:
  SERVICE_NAME: "blog_api"
  POSTGRES_HOST: "postgres-blog-api"
  POSTGRES_PORT: "5432"
  MINIO_ENDPOINT: "minio:9000"
  CORS_DOMAIN: "example.com"
