apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-api-config
data:
  SERVICE_NAME: "blog_api"
  POSTGRES_HOST: "postgres-prof-assistant"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "postgres"
  JWT_ALGORITHM: "HS256"
  INSPECT_TOKEN_URL: "http://personal-app/api/v1/auth/inspect_token"
  MINIO_ENDPOINT: "minio.test.prof-stankin.ru"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minio123"
  MINIO_SECURE: "True"
  MINIO_BUCKET_NAME: "blog-images"
  MINIO_BASE_URL: "https://minio.test.prof-stankin.ru"
  CORS_DOMAIN: "https://admin.test.prof-stankin.ru,https://api-blog.test.prof-stankin.ru"
