apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-api-config
data:
  SERVICE_NAME: "blog_api"
  POSTGRES_HOST: "postgres-schedule-api"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "postgres"
  JWT_ALGORITHM: "HS256"
  INSPECT_TOKEN_URL: "http://schedule-api-svc/auth/inspect"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minio123"
  MINIO_SECURE: "False"
  MINIO_BUCKET_NAME: "blog"
  MINIO_BASE_URL: "https://minio.test.prof-stankin.ru"
  CORS_DOMAIN: "https://admin.test.prof-stankin.ru,https://api-blog.test.prof-stankin.ru"
