apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-blog-api-cors@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api-blog.test.prof-stankin.ru
      secretName: blog-api-tls
  rules:
    - host: api-blog.test.prof-stankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-api-svc
                port:
                  number: 80
