apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profstankin-ingress
  namespace: prof-prod-apps
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: prof-prod-apps-front-api-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: prof-stankin.ru
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blog-api-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profstankin-front-svc
                port:
                  number: 80
  tls:
    - hosts:
        - prof-stankin.ru
      secretName: profstankin-tls
