apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profstankin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  tls:
    - hosts:
        - test.prof-stankin.ru
      secretName: profstankin-tls
  rules:
    - host: test.prof-stankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profstankin-front-svc
                port:
                  number: 80
