apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

configMapGenerator:
  - name: front-config
    literals:
      - VITE_SERVER_API=/api

images:
- name: chouqe/profstankin-frontend
  newName: chouqe/profstankin-front
  newTag: 0ee68c4
