apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
images:
- name: chouqe/profstankin-frontend
  newName: chouqe/profstankin-front
  newTag: 906e2e4
- name: profstankin-front-image
  newName: chouqe/profstankin-front
  newTag: 06c94b3
