apiVersion: v1
kind: ConfigMap
metadata:
  name: personal-app-config
data:
  POSTGRES_HOST: "postgres-personal"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "user"
  POSTGRES_MIGRATIONS_DIR: "/migrations"
  POSTGRES_SSLMODE: "disable"
  S3_ENDPOINT: "minio:9000"
  S3_SECURE: "false"
  S3_BUCKET_NAME: "personal-images"
