apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - api.test.prof-stankin.ru
      secretName: personal-app-tls
  rules:
    - host: api.test.prof-stankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-app
                port:
                  number: 80
