apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
- ingress.yaml
- secrets.yaml
images:
- name: personal-app-image
  newName: chouqe/personal-app
  newTag: 8055b0e
