apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config-blog
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }
    loki.write "local" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }
    local.file_match "logs" {
      path_targets = [{"__address__" = "localhost", "filename" = "/project/logs/*.json"}]
    }
    loki.source.file "blog_logs" {
      targets    = local.file_match.logs.targets
      forward_to = [loki.write.local.receiver]
    }
