apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
        - name: application
          image: blog-api-image
          ports:
            - containerPort: 7070
          readinessProbe:
            httpGet:
              path: /api/v1/categories/
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/categories/
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: blog-api-config
            - secretRef:
                name: blog-api-secrets
          volumeMounts:
            - name: logs
              mountPath: /project/logs
        - name: alloy
          image: grafana/alloy:latest
          args:
            [
              "run",
              "--server.http.listen-addr=0.0.0.0:8989",
              "/etc/alloy/config.alloy",
            ]
          volumeMounts:
            - name: alloy-conf
              mountPath: /etc/alloy
            - name: logs
              mountPath: /project/logs
      volumes:
        - name: logs
          emptyDir: {}
        - name: alloy-conf
          configMap:
            name: alloy-config-blog
