apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - alloy-config.yaml
  - service.yaml
images:
  - name: blog-api-image
    newName: chouqe/blog-api-application
    newTag: latest
