apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-api-config
data:
  DEBUG: "False"
  POSTGRES_HOST: "postgres-schedule-api"
  REDIS_HOST: "redis-schedule-api"
  EOS_URL: "https://edu.stankin.ru"
  EOS_SCHEDULE_CHECK_TIME: "03:00"
  PYTHONPATH: "/project/app"
