apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-api-config
data:
  DEBUG: "False"
  POSTGRES_HOST: "postgres-schedule-api"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "postgres"
  REDIS_HOST: "redis-schedule-api"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  EOS_URL: "https://edu.stankin.ru"
  EOS_SCHEDULE_CHECK_TIME: "03:00"
  PYTHONPATH: "/project/app"
