apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prof-test-db

resources:
  - deployment.yaml
  - service.yaml
  - ingress-api.yaml
  - ingress-console.yaml

configMapGenerator:
  - name: minio-db-config
    envs:
      - configmap.yaml

secretGenerator:
  - name: minio-db-secrets
    envs:
      - secrets.yaml
