apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-api
  template:
    metadata:
      labels:
        app: schedule-api
    spec:
      containers:
        - name: api
          image: chouqe/schedule-api:latest
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: schedule-api-config
            - secretRef:
                name: schedule-api-secrets
