apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-admin
  template:
    metadata:
      labels:
        app: blog-admin
    spec:
      containers:
        - name: frontend
          image: chouqe/blog-admin-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_BLOG_API_URL
              value: "https://api-blog.test.prof-stankin.ru" # Обновлено
            - name: VITE_SERVER_API
              value: "https://admin.test.prof-stankin.ru"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-admin-svc
spec:
  selector:
    app: blog-admin
  ports:
    - port: 80
      targetPort: 80
