apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-admin
  template:
    metadata:
      labels:
        app: blog-admin
    spec:
      containers:
        - name: frontend
          image: chouqe/blog-admin-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-admin-svc
spec:
  selector:
    app: blog-admin
  ports:
    - port: 80
      targetPort: 80
