apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - profstankin.ru
        - admin.profstankin.ru
        - api.profstankin.ru
      secretName: main-site-tls
  rules:
    - host: profstankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profstankin-front-svc
                port:
                  number: 80
    - host: admin.profstankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-admin-svc
                port:
                  number: 80
    - host: api.profstankin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: schedule-api-svc
                port:
                  number: 80
